지도 API 연결
yaejin9503/mapProject pull request #2
Opened 2024-01-05 09:53 UTC by yaejin9503

## 작업 내용

- src/component/common 폴더 생성
- 카카오 Map API 적용 

## 리뷰어에게 하고싶은 말
카카오 Map API랑 네이버 Map API 둘다 찾아봤는데, 
빠르게 프로젝트 하기엔 카카오 Map이 좋은것 같아서 카카오 API 로 선택했습니다!

2024-01-06 07:51 UTC, Godsenal requested changes
lint / ts 전부 에러가 나고 있는데 이부분 신경쓰면서 작업해주세요!

2024-01-06 07:51 UTC, Godsenal commented on .vscode/extensions.json
> +    "dbaeumer.vscode-eslint"
지도 API 연결 작업 -> #1 PR 머지

위 순서로 작업하셔서 master -> develop 머지를 하신 것 같은데, 이런 경우는 PR 올리기전 리베이스 하시면 불필요한 (이미 리뷰한) 커밋을 볼 필요없어서 리뷰하는 입장에서 더 좋아요

2024-01-06 07:51 UTC, Godsenal commented on src/App.tsx
> +// import { useState } from 'react'
이거 제거하지 않고 주석처리로 하신 이유가 있으신가요?

2024-01-06 07:51 UTC, Godsenal commented on .eslintrc.cjs
> +  parserOptions: {
이 설정이 들어간 이유를 모르겠어요.
이 커밋 내용과 전혀 연관 없는 부분이라 커밋 분리와 설명이 필요해보여요

2024-01-06 07:51 UTC, Godsenal commented on src/components/common/KakaoMap.tsx
> +    const container = document.getElementById('map'); //지도를 담을 영역의 DOM 레퍼런스
가능하면 전역으로 탐색하는 elemet id보다는 ref를 사용하는게 좋을 것 같아요.

2024-01-06 07:51 UTC, Godsenal commented on src/components/common/KakaoMap.tsx
> +export default function KakaoMap(props : any){
typescript 학습의 목적도 있으니 any 는 최대한 지양하면 좋겠어요

2024-01-08 04:40 UTC, yaejin9503 commented on src/App.tsx
> +// import { useState } from 'react'
나중에 쓰일 꺼라고 생각되어 주석처리 하였습니다..! 사용되지 않는 경우 그냥 제거하는게 좋을까요?!

2024-01-08 04:41 UTC, yaejin9503 commented on .eslintrc.cjs
> +  parserOptions: {
이전에 오류 났을 때, 해결하는 과정에서 추가 작성했던 부분인데.. 빼는 걸 까먹고 그대로 pr에 반영했네요 흑흑 ㅠㅠ 
좀 더 신경써서 pr 하도록 하겠습니다!

2024-01-08 05:05 UTC, yaejin9503 commented on .vscode/extensions.json
> +    "dbaeumer.vscode-eslint"
rebase 라는 게  
 - 작업물을 작업 브랜치에 커밋 , 푸시까지 진행한 후에 merge 하려는 브랜치 ( main ) 을 rebase 하면 되는걸까요?!.. rebase 후에 pr 요청하는게 순서가 맞나 궁금해서요!

2024-01-08 13:08 UTC, Godsenal commented on src/App.tsx
> +// import { useState } from 'react'
네네 주석처리하시는것도 좋지만 리뷰어 입장에서는 어떤 의도인지 알기 힘들기 때문에 설명정도는 적어주셔도 좋을 것 같아요!

2024-01-08 13:08 UTC, Godsenal commented on .vscode/extensions.json
> +    "dbaeumer.vscode-eslint"
네네 맞아요.
이번 같은 경우에는 이 브랜치 작업 PR을 올리기전에 main이 바뀌었기 때문에 리뷰어 입장에서는 merge 커밋을 볼 필요가 없으니 rebase 를 해주시면 좋죠!

2024-01-09 05:39 UTC, Godsenal commented
리뷰반영이 모두 완료되었으면 `Re-request review` 한번 눌러주세요!

2024-01-11 05:42 UTC, Godsenal approved these changes
수고하셨어요~~

카카오 API 관련 타입을 일부 정의해놓은 패키지가 있어서 이걸 설치해서 사용하셔도 좋을 것 같아요.
https://www.npmjs.com/package/kakao.maps.d.ts

2024-01-12 08:31 UTC, merged