Feat: "지도 마커 기능 구현"
yaejin9503/mapProject pull request #4
Opened 2024-01-14 15:11 UTC by yaejin9503

목업 데이터를 기반으로 한 지도 마커 기능 구현

## 작업 내용
- json 파일을 기반으로 지도 마커 기능을 구현 

## 리뷰어에게 하고싶은 말
- 렌더링 시 마커가 나타나지 않고.. 파일을 저장해야 뒤늦게 마커가 나타납니다 흑..ㅠㅠ
-  중복된 주소가 많아서 중복 주소 제거하는 state를 추가해서 작성했는데.. 저 방법이 맞는지 모르겠네요..ㅠㅠ
- 스타일 라이브러리로는 Tailwind CSS  + tailwindui (HeadlessUI)  로 하고자 합니다 
 →이유로는 사전에 정의된 스타일 클래스를 사용하여 디자인하는 방식을 채택하고 있어, 기능 구현에 집중할 수 있는 시간이 증가 될 것 같음.

2024-01-15 14:09 UTC, Godsenal requested changes
리뷰하는데 병목이 되는 요소가 있어서 커맨트 남겨요.

**린트와 코드 컨벤션 관련**
불필요한 주석이나 console은 다 제거해주세요. 리뷰어가 리뷰에 집중할 수 있어야 좋은 퀄리티의 리뷰도 코드에만 집중할 수 있다고 생각하는데 지금은 린트에러와 여러 주석들이 그대로 노출되고 있어요. 이 부분 정리해서 올려주시고 개발하실 때도 신경써주면서 적용해주세요.

사용하시는 에디터에 린트 설정이 안되어있는 것 같기도한데, 한번 확인해주세요.

**커밋 크기**
한 커밋의 크기가 너무 커서 동작별로 리뷰하는데 병목이 되고 있어요.
동작가능한 최소단위로 최대한 쪼개주세요. 예를들어 이 PR 같은 경우
- 데이터 패칭 로직
- 마커 그리는 로직 
- infowindow 처리하는 로직
최소한 이정도는 쪼갰을 것 같아요. 그래야 각 커밋별 로직에 집중하여 더 좋은 리뷰 드릴 수 있을 것 같아요.

2024-01-15 14:09 UTC, Godsenal commented on package.json
> +    "cheerio": "^1.0.0-rc.12",
요건 어디에 쓰는걸까용?

2024-01-15 14:09 UTC, Godsenal commented on package.json
> +    "lodash": "^4.17.21",
lodash는 번들 사이즈가 커서 SPA에서 사용할 때 고려해야하는 부분이 조금 있는데 이건 성능개선 주차에 한번 다시 이야기해보죠 ㅎㅎ

2024-01-15 14:09 UTC, Godsenal commented on src/components/common/KakaoMap.tsx
> +const { kakao } = window;
`kakao.map.d.ts` 파일은 글로벌에 kakao namespace를 생성해요.
지금은 타입의 이점을 전혀 누리고 있지 않을 것 같은데 맞나요?

2024-01-15 14:09 UTC, Godsenal commented on src/components/common/KakaoMap.tsx
> +    const map = new kakao.maps.Map(container, options); //지도 생성 및 객체 리턴
맵을 생성하는 로직과 마커를 생성하는 로직이 분리될 필요가 있어보여요.
`props.data` 가 바뀐다고 맵을 재생성하고 싶은게 아니라 마커만 다시 그리고 싶은게 아닌가 싶어요.

지금은 데이터가 바뀔때마다 불필요하게 맵을 재구성하고 있어서요.

2024-01-15 14:09 UTC, Godsenal commented on src/App.tsx
> +    fetchData();
fetchData는 비동기이기 때문에 당연히 이 아래 코드에서 `noDupplicateAddress` 는 초기값인 `[]` 일 수 밖에 없어요.
javascript의 비동기 동작과 관련해서 조금 더 찾아보시는게 좋을 것 같아요.

아마 이부분을 해소하기 위해 `flushSync` 를 사용하셨을 것 같은데, `flushSync`는 비동기적인 **state 업데이트** 를 바로 실행하도록 해주는거라 이 로직과는 전혀 무관해요. (flushSync의 실제 사용 케이스에 대해서도 알아오시면 좋겠어요)

이 부분을 정상 동작하게 하려면 이 effect내에서 fetchData의 비동기로직(promise)이 resolve 된 후 다음 로직들이 수행되도록 하시면 될 것 같아요.

2024-01-15 15:59 UTC, yaejin9503 commented on src/components/common/KakaoMap.tsx
> +    const map = new kakao.maps.Map(container, options); //지도 생성 및 객체 리턴
맵을 생성하는 로직과  마커를 생성하는 로직을 분리 하는 방법을 잘 모르겠어서요....! 
로직을 분리 하려면, 컴포넌트를 따로 가져가는 게 맞는 건가요..? 
예를 들면 
- 마커를 생성하는 컴포넌트 
- 지도를 생성하는 컴포넌트 
이런식으로 가져가서 각각의 state값을 props로 전달해주는 방법이...맞나용..??..

2024-01-15 16:05 UTC, yaejin9503 commented on src/components/common/KakaoMap.tsx
> +const { kakao } = window;
파일의 이점을 활용하려면 
`const map: kakao.maps.Map ` 이런식으로 타입을 지정해주면 될까요?! 
아니면 원래 
```
declare global {
  interface Window {
    kakao: any;
  }
}
```

이렇게 작성해주고 있었는데 

```
declare global {
  interface Window {
    kakao: kakao.maps;
  }
}
```
이렇게 바꾸는게 해당 라이브러리의 이점을 사용한 방식일지 궁금합니다!

2024-01-15 16:08 UTC, yaejin9503 commented on package.json
> +    "cheerio": "^1.0.0-rc.12",
- axios
- cheerio 
는 크롤링 할 때 사용했던 라이브러리들인데 사용 하지 않아서 삭제 처리 했습니다. 

위의 @types/lodash는 중복데이터 제거할 때 사용하려고 설치했었습니다!

2024-01-16 09:36 UTC, Godsenal commented on src/components/common/KakaoMap.tsx
> +const { kakao } = window;
저희는 web package이기 때문에 window = global 이라 `window` 참조를 안하고 바로 kakao를 참조하는 방식으로도 사용할 수 있고, 확장성을 고려하면 말씀주신대로 window에 지정해주는게 좋아보여요

2024-01-16 09:39 UTC, Godsenal commented on src/components/common/KakaoMap.tsx
> +    const map = new kakao.maps.Map(container, options); //지도 생성 및 객체 리턴
위 로직은 UI와 관련된 부분이 아니기 때문에 컴포넌트보다는 hook을 통한 분리가 좋을 것 같아요.

https://react.dev/learn/synchronizing-with-effects#how-to-write-an-effect

이부분을 참조하셔서 effect 의 deps를 조정하는 식으로 적용하면 좋을 것 같아요.

어떤 값이 변경됐을 때 (또는 어떤 라이프사이클에서) 맵 초기화를 해야하는지 / 어떤 값이 변경됐을 때 마커를 그려줘야하는지

이렇게 분류해서 작업해보시면 좋을 것 같습니다.

2024-01-17 07:46 UTC, yaejin9503 commented
질문 
- fetch 에서 resolve 를 추가하여 로직이 끝난 후 set 하도록 했는데, 여전히 props.data에는 받아온 데이터인 latitude, longitude 를 빼놓고 데이터를 넘겨서 페이지 재렌더링이 일어나지 않는 것 같습니다...  
- kakaoMap 과 kakaoMapMarker로 분리했는데 이렇게 분리하면 컴포넌트 형식으로 분리하게 되는 건걸까요? 
  참고 링크도 봤는데 이 방식이 맞는지 잘모르겠어서 질문드립니다..! 
- 제가 짠 코드는 props 형식으로 map를 넘겨주게 되는데 이렇게 되면, state를 초기화 할 때 어떻게 해줘야 될지 모르겠어서..일단 타입 에러 나는 채로 놔뒀습니다 !! ㅠㅠ 

![스크린샷 2024-01-17 오후 4 44 39](https://github.com/yaejin9503/mapProject/assets/54971846/b2df966f-e2c0-4cde-9dcb-398fc7b532ac)

보시면 마커가 렌더링 된 후, 데이터를 가져와서 마커 렌더링이 자꾸 실패하는 것 같은데..제가 유추한 문제점이 맞을까요,,?

2024-01-23 14:12 UTC, Godsenal requested changes
리뷰가 늦어졌네요. 고생하셨어요!
async/await 로 바꾸면 코드가 조금 더 이뻐질 것 같아요.

그리고 내일 에디터도 한번 같이 보시죠! prettier 같은 것도 적용하시면 좋을 것 같아요

2024-01-23 14:12 UTC, Godsenal commented on src/App.tsx
> +          const notDupplicate: Array<HouseInfo> = [];
`lodash` 도 디펜던시에 추가하셨던데 이런건 `lodash` 이용해도 좋을 것 같네요 ㅎㅎ

2024-01-23 14:12 UTC, Godsenal commented on src/App.tsx
> +          geocoder.addressSearch(house.address, function (result : Array<AddressFucResult> ,status :  kakao.maps.services.Status){
애로우 함수든 / function 이든 상관없는데 적어도 한 동작안해서는 통일되면 좋을 것 같아요. 가독성이 떨어질 수 있어서요

2024-01-23 14:12 UTC, Godsenal commented on src/App.tsx
> +  const [data, setData] = useState<Array<HouseInfo>>([]); //원본 데이터
이 `data` 와 `noDupplicateAddress` 는 필요없지 않나요?
어차피 `addGeocoderData` 가 위 데이터에 추가된 데이터가 있는 애들이니까요.

2024-01-23 14:12 UTC, Godsenal commented on src/App.tsx
> +        returnData.map((result) => {
데이터를 반환하는 경우 아니면 `map` 보다는 `foreach`를 사용해주세요~~

2024-01-23 14:12 UTC, Godsenal commented on src/App.tsx
> +            obj.longitude = result && Number(result?.x);
`result` 가 없을 수도 있나요?

없으면 여기서 이런 검증이 들어갈게 아니라 반복돌기전에 한번 체크하는 플로우가 좋아보여요.

2024-01-25 08:32 UTC, Godsenal approved these changes
고생하셨어요~~

2024-01-25 08:32 UTC, Godsenal commented on src/api/houseApi.ts
> +export const removeDupplicateAddress = async () => {
분리 잘 하셨는데요!

각 함수가 해당 역할만 하면 좋을 것 같아요.

`fetchData` 라는 함수가 뽑아져있는데 데이터 패칭은 어디서 하고 있지? 라고 생각 을 했었거든요.

즉 `removeDupplicateAddress` 라는 함수를 사용할 때 데이터 패칭을 할 거라고 생각이 들지 않아요. `addGeocoder` 도 마찬가지구요.

그래서 이걸 분리한다면 input -> output 을 활용해서 이런식으로 사용할 수 있을 것 같아요.

```
const houseData = await fetchData();
const uniqHouseData = await removeDupplicateAddress(houseData);
const houseWithGeocoder = await addGeocoder(uniqHouseData);
```

2024-01-26 08:55 UTC, merged