마커에 주택 가격 표시
yaejin9503/mapProject pull request #5
Opened 2024-01-29 05:04 UTC by yaejin9503

## 작업 내용
- 내 위치 기반으로 지도 렌더링 
- 스타일 적용을 위한 tailwind css 설치 및 적용 
- 1순위, 2-3순위의 가격차이를 보여주기 위한 옵션 필터 설정 
- 옵션값을 전역으로 관리하기 위해 전역 상태 라이브러리 설정 및 적용 

## 리뷰어에게 하고싶은 말
지도 마커에 가격만 표기하기에는 너무 작업량이 없어서 
하고 싶은 기능 이것저것 추가해봤습니다...ㅎㅎㅎ... 

## 어려웠던 점 및 질문 
1. 현재 위치 기반으로 지도 렌더링 하고 싶어서 추가했더니 위치가 늦게 불러와지면 생성되었던 마커가 사라지는..버그 발생 
    -> 비동기 처리 + 경도 위도 변경되면 데이터를 다시 불러오게 변경했더니 해당 버그는 다시 일어나지 않음.. 

이렇게 처리해놓긴 했는데 괜찮은 방법인지는 잘 모르겠습니다..ㅎ... 

2. 옵션값을 전역으로 관리하는게 맞는 방법일까요? 제 생각에는 전역으로 관리 하지 않으면 그 필터값을 여러 컴포넌트에서 사용할 수 없을 것 같아서 일단 전역으로 빼놓긴 했습니당...

2024-01-31 12:17 UTC, Godsenal reviewed
> 현재 위치 기반으로 지도 렌더링 하고 싶어서 추가했더니 위치가 늦게 불러와지면 생성되었던 마커가 사라지는..버그 발생
-> 비동기 처리 + 경도 위도 변경되면 데이터를 다시 불러오게 변경했더니 해당 버그는 다시 일어나지 않음..
이렇게 처리해놓긴 했는데 괜찮은 방법인지는 잘 모르겠습니다..ㅎ...

더 근본적인 원인을 해결해주세요!
현재 에러가 발생하는 원인은 coordinate가 바뀔 때마다 map을 재생성하기 때문이에요.
대신 map의 이동만 옮길 수 있도록 해주세요.

> 옵션값을 전역으로 관리하는게 맞는 방법일까요? 제 생각에는 전역으로 관리 하지 않으면 그 필터값을 여러 컴포넌트에서 사용할 수 없을 것 같아서 일단 전역으로 빼놓긴 했습니당...

rank라는 값이 로컬 컴포넌트 별로 다른 값을 가지지 않는 다면, 즉 해당 값이 바뀌었을 때 참조하는 모든 곳이 바뀌는 값이라면 zustand로 관리하시면 될 것 같아요 ㅎㅎ

2024-01-31 12:17 UTC, Godsenal commented on src/App.tsx
> +  const getMyGeoCoder = async () => {
사용되는 곳에서만 컨텍스트를 공유할 수 있도록 effect 내부로 옮겨주세요!

2024-01-31 12:17 UTC, Godsenal commented on src/api/userApi.ts
> +export const getMyGeoLocation = (): number[] => {
함수 내부 promise 동작을 사용하는 쪽에서 기다릴 수 있도록 promise를 리턴해주세요!

2024-01-31 12:17 UTC, Godsenal commented on src/components/options/OptionSearch.tsx
> +/* eslint-disable @typescript-eslint/no-unused-vars */
불필요한 주석은 전체적으로 제거해주세요

2024-01-31 12:17 UTC, Godsenal commented on src/components/options/OptionSearch.tsx
> +    firstBtn.current?.classList.toggle('bg-white');
돔을 명시적으로 조작하기보다는 state에 따라 선언적으로 className이 변경될 수 있도록 해주세요.

https://react.dev/learn/reacting-to-input-with-state#how-declarative-ui-compares-to-imperative

요걸 한번 보시면 더 좋을 것 같아요!

2024-02-07 09:55 UTC, Godsenal requested changes
리뷰드린 부분 전부 비슷한 내용인 것 같아요!

https://react.dev/learn/choosing-the-state-structure
요것도 보시면 좋을 것 같아서 (이미 보셨겠지만?) 링크드려요

2024-02-07 09:55 UTC, Godsenal commented on src/components/common/KakaoMap.tsx
> +    setContainerState(mapDiv.current as HTMLDivElement);
`containerState` / `optionState` 가 둘다 상태로 관리될 필요가 없는 값들인 것 같아요.
요거 state로 뽑으신 이유가 있으신가요?

2024-02-07 09:55 UTC, Godsenal commented on src/components/options/OptionSearch.tsx
> +  const [firstBtnClassName, setFirstBtnClassName] = useState(
요거 `className` 을 상태로 저장하신 이유가 있나요?

상태의 기본값들은 사실상 고정으로 적용되는 스타일일텐데, 상태 추적이 어려울 것 같아요.
바뀌는 className을 상태로 가지는 게 아니라 바뀌는 rank에 따라 className이 파생된다고 생각하고 작업을 해보시면 좋을 것 같아요.

그렇게 생각하면 저희는 이미 rank라는 state가 있으니 별도의 state는 필요없곘죠??

2024-02-07 09:55 UTC, Godsenal commented on src/components/units/KakaoMapMarker.tsx
> +  const [marker, setMarker] = useState<Array<HouseInfo> | undefined>([]);
얘도 별도 상태로 두기보단 파생상태로 관리를 해보시면 좋을 것 같아요.
props.data와 결국 동일한 값이니까요

2024-02-13 05:56 UTC, yaejin9503 commented
kakaoMapMarker는 추가된 코드랑 함께 보시는게 좋을 것 같아서 다음 pr때 커밋하겠습니다!

2024-02-14 10:45 UTC, Godsenal approved these changes
깔끔해졌네요 ㅎㅎ

2024-02-14 11:04 UTC, merged