자동 완성 검색 기능 추가
yaejin9503/mapProject pull request #8
Opened 2024-03-05 08:40 UTC by yaejin9503

## 작업 내용
- 자동 완성 검색 기능 추가 
- 확대, 축소 및 자잘한 기능 추가 

## 리뷰어에게 하고싶은 말
멘토님이 말씀해주신 방향으로는 구현을 못한 것 같습니당 ㅠ

라이브러리 사용해서 컴포넌트 자체를 promise화 해서 suspense가 적용되게 해야되는데
일단 직면한 문제점이 
-> 라이브러리에서 원하는 방법으로 만들자니 검색할 때마다 가져오는 게 안되더라구요;; 
    ( 아마 제가 적용을 잘 못해서 그런 듯 싶습니다 ㅠ ) 

그래서 일단 usedeferredvalue이용해서 lazy로 컴포넌트를 불러오고 Suspense로 적용해두는 방식으로..구현하였습니다 !

2024-03-07 13:45 UTC, Godsenal commented on package.json
> +    "@suspensive/react-await": "^0.0.16",
요건 제거하셔도 될듯요~!

2024-03-07 13:45 UTC, Godsenal commented on src/components/options/units/SearchResult.tsx
> +  if (data && Array.isArray(data) && data.length > 0) {
상태에 따라 조건문의 순서를 바꿔주면 조금 더 명확해질 수 있을 것 같아요.
나올 수 있는 상태가

1. 쿼리가 없음
2. 쿼리에 해당하는 검색결과가 없음
3. 검색결과 있음

요렇게 3개일텐데요.
쿼리가 없는 경우는 1번인 경우에는 아예 이 컴포넌트를 랜더할 필요가 없어보이고, 2번인 경우 검색결과 없음, 3번인 경우 리스트 리턴하는 방식으로요.

2024-03-07 13:45 UTC, Godsenal commented on src/components/options/units/SearchResult.tsx
> +      data && (
위에서 이미 거르고 있으니까 필요 없어보여요.

2024-03-07 13:45 UTC, Godsenal commented on src/store/mapStore.ts
> +  myLongitude: number;
요런 값들 의미상 null이 가능하도록 넣어주는게 좋긴해요 ㅎㅎ
버그가능성도 줄어들고요!

2024-03-08 05:16 UTC, yaejin9503 commented
피드백대로 조건문을 수정 했는데, 
data가 없을 때는 바로 빈 요소를 return하게 하는 방식으로 처리하면 될까요?!

2024-03-14 15:51 UTC, Godsenal requested changes

2024-03-14 15:51 UTC, Godsenal commented on src/components/options/units/SearchResult.tsx
> +  /**
여기서 몇가지 리뷰하고 싶은 포인트가 있네요!

일단 쿼리가 없을 때는 이 컴포넌트를 사용하는 쪽에서 랜더링을 하면 더 간결해질 수 있을 것 같아요. 이 컴포넌트는 쿼리에 대한 결과값을 내주는 컴포넌트니까요!

그리고 `<></>` 요렇게 리턴하는 코드들이 많이 보이는데, 이렇게 랜더링할 내용이 없는 경우 `return null` 을 하면 돼요. Fragment는 한 컴포넌트에서 엘리먼트를 그룹화하고자할 떄 사용해요.


위 내용을 바탕으로 처리해보면 코드가 더 간결해질 수 있을 것 같아요.

2024-03-22 09:49 UTC, Godsenal approved these changes
수고 많으셨어요~~

2024-03-23 04:24 UTC, merged